version: '3'
services:
  dotproject:
    image: "dotproject:2.1.9-1"
    ports:
     - "8080:80"
    networks:
      - myoverlaynet
    volumes:
      - ./dotproject.conf:/var/www/app/includes/config.php
  db:
    image: mysql:5.5
    restart: always
    environment:
      MYSQL_DATABASE: 'dotproject'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'dp_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: ''
      # Password for root access
      MYSQL_ROOT_PASSWORD: ''
    networks:
      - myoverlaynet
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:

networks:
  myoverlaynet:
